
![Illustration of silhouetted heads](mentalhealth.jpg)


Does going to university in a different country affect your mental health? A Japanese international university surveyed its students in 2018 and published a study the following year that was approved by several ethical and regulatory boards.

The study found that international students have a higher risk of mental health difficulties than the general population, and that social connectedness (belonging to a social group) and acculturative stress (stress associated with joining a new culture) are predictive of depression.

Explore the students data using PostgreSQL to find out if you would come to a similar conclusion for international students and see if the length of stay is a contributing factor.

Here is a data description of the columns you may find helpful.

In [1]:
import pandas as pd
import sqlite3

In [3]:
df=pd.read_csv('students.csv')

,inter_dom,region,gender,academic,age,age_cate,stay,stay_cate,japanese,japanese_cate,...,friends_bi,parents_bi,relative_bi,professional_bi,phone_bi,doctor_bi,religion_bi,alone_bi,others_bi,internet_bi
0,Inter,SEA,Male,Grad,24.0,4.0,5.0,Long,3.0,Average,...,Yes,Yes,No,No,No,No,No,No,No,No
1,Inter,SEA,Male,Grad,28.0,5.0,1.0,Short,4.0,High,...,Yes,Yes,No,No,No,No,No,No,No,No
2,Inter,SEA,Male,Grad,25.0,4.0,6.0,Long,4.0,High,...,No,No,No,No,No,No,No,No,No,No
3,Inter,EA,Female,Grad,29.0,5.0,1.0,Short,2.0,Low,...,Yes,Yes,Yes,Yes,No,No,No,No,No,No
4,Inter,EA,Female,Grad,28.0,5.0,1.0,Short,1.0,Low,...,Yes,Yes,No,Yes,No,Yes,Yes,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
cnn = sqlite3.connect('jupyter_sql_tutorial.db')

df.to_sql('students', cnn, if_exists='replace', index=False)

%load_ext sql

%sql sqlite:///jupyter_sql_tutorial.db

In [7]:
%%sql

SELECT * 
FROM students
LIMIT 10;

 * sqlite:///jupyter_sql_tutorial.db
Done.

[('Inter', 'SEA', 'Male', 'Grad', 24.0, 4.0, 5.0, 'Long', 3.0, 'Average', 5.0, 'High', None, 'Yes', 'No', 'No', 'No', 0.0, 'Min', 34.0, 23.0, 9.0, 11.0, 8.0, 11.0, 2.0, 27.0, 91.0, 5.0, 5.0, 6.0, 3.0, 2.0, 1.0, 4.0, 1.0, 3.0, 4.0, None, 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'),
 ('Inter', 'SEA', 'Male', 'Grad', 28.0, 5.0, 1.0, 'Short', 4.0, 'High', 4.0, 'High', None, 'No', 'No', 'No', 'No', 2.0, 'Min', 48.0, 8.0, 7.0, 5.0, 4.0, 3.0, 2.0, 10.0, 39.0, 7.0, 7.0, 7.0, 4.0, 4.0, 4.0, 4.0, 1.0, 1.0, 1.0, None, 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'),
 ('Inter', 'SEA', 'Male', 'Grad', 25.0, 4.0, 6.0, 'Long', 4.0, 'High', 4.0, 'High', 'Yes', 'Yes', 'No', 'No', 'No', 2.0, 'Min', 41.0, 13.0, 4.0, 7.0, 6.0, 4.0, 3.0, 14.0, 51.0, 3.0, 3.0, 3.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, None, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'),
 ('Inter', 'EA', 'Female', 'Grad', 29.0, 5.0, 1.0, 'Short', 2.0, 'Low', 3.0, 'Average', 'No', 'No', 'No', 'No', 'No', 3.0, 'Min', 37.0, 16.0, 10.0, 10.0, 8.0, 6.0, 4.0, 21.0, 75.0, 5.0, 5.0, 5.0, 5.0, 5.0, 2.0, 2.0, 2.0, 4.0, 4.0, None, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No'),
 ('Inter', 'EA', 'Female', 'Grad', 28.0, 5.0, 1.0, 'Short', 1.0, 'Low', 3.0, 'Average', 'Yes', 'No', 'No', 'No', 'No', 3.0, 'Min', 37.0, 15.0, 12.0, 5.0, 8.0, 7.0, 4.0, 31.0, 82.0, 5.0, 5.0, 5.0, 2.0, 5.0, 2.0, 5.0, 5.0, 4.0, 4.0, None, 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'No'),
 ('Inter', 'SEA', 'Male', 'Grad', 24.0, 4.0, 6.0, 'Long', 3.0, 'Average', 4.0, 'High', 'Yes', 'No', 'No', 'No', 'No', 6.0, 'Mild', 38.0, 18.0, 8.0, 10.0, 8.0, 7.0, 3.0, 29.0, 83.0, 6.0, 5.0, 4.0, 2.0, 1.0, 1.0, 2.0, 1.0, 5.0, 1.0, None, 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No'),
 ('Inter', 'SA', 'Male', 'Grad', 23.0, 4.0, 1.0, 'Short', 3.0, 'Average', 5.0, 'High', 'Yes', 'No', 'No', 'No', 'No', 3.0, 'Min', 46.0, 17.0, 6.0, 10.0, 5.0, 3.0, 2.0, 15.0, 58.0, 7.0, 5.0, 7.0, 2.0, 2.0, 1.0, 5.0, 1.0, 1.0, 1.0, None, 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No'),
 ('Inter', 'SEA', 'Female', 'Grad', 30.0, 5.0, 2.0, 'Medium', 1.0, 'Low', 1.0, 'Low', 'Yes', 'Yes', 'Yes', 'No', 'No', 9.0, 'Mild', 41.0, 16.0, 20.0, 19.0, 15.0, 11.0, 6.0, 40.0, 127.0, 7.0, 2.0, 2.0, 2.0, 6.0, 2.0, 1.0, 1.0, 3.0, 1.0, None, 'Yes', 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No'),
 ('Inter', 'SEA', 'Female', 'Grad', 25.0, 4.0, 4.0, 'Long', 4.0, 'High', 4.0, 'High', 'No', 'No', 'No', 'Yes', 'Other', 7.0, 'Mild', 36.0, 22.0, 12.0, 13.0, 13.0, 10.0, 6.0, 33.0, 109.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, None, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No'),
 ('Inter', 'Others', 'Male', 'Grad', 31.0, 5.0, 2.0, 'Medium', 1.0, 'Low', 4.0, 'High', 'Yes', 'Yes', 'No', 'No', 'No', 3.0, 'Min', 48.0, 8.0, 4.0, 5.0, 12.0, 3.0, 2.0, 17.0, 51.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, None, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No')]

In [17]:
%%sql

SELECT stay, COUNT(inter_dom) AS count_int, 
       ROUND(AVG(todep), 2) AS average_phq, 
       ROUND(AVG(tosc), 2) AS average_scs, 
       ROUND(AVG(toas), 2) AS average_as
FROM students  -- Use the table name here, not the CSV file
WHERE stay IS NOT NULL AND inter_dom = 'Inter'
GROUP BY stay
ORDER BY stay DESC;

 * sqlite:///jupyter_sql_tutorial.db
Done.

[(10.0, 1, 13.0, 32.0, 50.0),
 (8.0, 1, 10.0, 44.0, 65.0),
 (7.0, 1, 4.0, 48.0, 45.0),
 (6.0, 3, 6.0, 38.0, 58.67),
 (5.0, 1, 0.0, 34.0, 91.0),
 (4.0, 14, 8.57, 33.93, 87.71),
 (3.0, 46, 9.09, 37.13, 78.0),
 (2.0, 39, 8.28, 37.08, 77.67),
 (1.0, 95, 7.48, 38.11, 72.8)]